security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        # use your user class name here
        App\Entity\Korisnici:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: bcrypt
            cost: 12
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Korisnici
                # the property to query by - e.g. username, email, etc
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:

            anonymous: ~
            guard:
                authenticators:
                    - App\Security\PrijavaAuthAuthenticator

            logout:
                 path:   /odjava
                 target: /

            # https://symfony.com/doc/current/security/form_login_setup.html


    access_control:
         - { path: ^/upisnilist, roles: ROLE_STUDENT }
         - { path: ^/studenti, roles: ROLE_MENTOR }
